### ISSUE TITLE
registry_secret_name usage without registries config

### ISSUE THREAD

**Issue by cafo13** [lacework/helm-charts#161]
Hi there!

I am currently setting up the lacework proxy scanner to scan our on premise harbor registry. I would like to set this up with the lacework proxy scanner helm chart from this repository.
I am not sure, if there is a problem with the handling of the config.registry_secret_name value or if I maybe don't really understand this, hopefully someone could help me here. :)

From the docs (https://docs.lacework.com/onboarding/integrate-proxy-scanner) I assumed, that I can either set the value config.registries or config.registry_secret_name and not both at the same time. So I want to set only the config.registry_secret_name. The problem I am encountering is, that when I provide a secret with the registries config in it and name it, e.g. "lacework-proxy-registries", and set the name in the config.registry_secret_name value, there will be no volume for the registries in the pod as the helm templating is setting not adding this when config.registries is not set.

My example values.yaml:
```
config:
  static_cache_location: /opt/lacework
  scan_public_registries: true
  lacework:
    account_name: <our account>
    integration_access_token: 
      existingSecret:
        name: lacework-proxy-scanner-access-token
        key: LACEWORK_PROXY_SCANNER_ACCESS_TOKEN
  default_registry: <our harbor registry URL>
  registry_secret_name: lacework-proxy-registries
```

I forked this repo and tried to change the behaviour within this Pull request, just in case I understand all correctly and not missing something, that could fix the behaviour, right? https://github.com/lacework/helm-charts/pull/160
