### ISSUE TITLE
lacework-agent v6.3.0: `anonymizeIncoming` is listed as optional but chart fails if not included in the values

### ISSUE THREAD

**Issue by laconc** [lacework/helm-charts#169]
Looks like [.laceworkConfig.anonymizeIncoming](https://github.com/lacework/helm-charts/pull/159/files#diff-23423a609e176bf18d8c78f4e81a14ee79a47a063ff9f40b5f84e2215fe28ac7R210-R219) was introduced in v6.3.0 as an optional field, as well as the child value `.netmask`. Unfortunately, attempting to deploy it results in

```
Error: values don't meet the specifications of the schema(s) in the following chart(s):
lacework-agent:
- laceworkConfig.anonymizeIncoming: netmask is required
```

I can get past it by including the `.laceworkConfig.anonymizeIncoming` key with a null value, in my values.

I'm unable to diagnose it further at the moment and will be moving forward with that workaround. If I was debugging this, I'd check to see if there's a conflict with `values.yaml` and `.netmask` being set as a required value of `.laceworkConfig.anonymizeIncoming`.

**Comment by cirego** [comment]
Hell @laconc, can you share the `values.yaml` and/or `--set` options that you are using? Did you specify the `anonymizeIncoming` field in your values?

**Comment by lorelei-rupp-imprivata** [comment]
This is driving me nuts right now
I just get 
```
Error: values don't meet the specifications of the schema(s) in the following chart(s):
lacework:
- laceworkConfig.anonymizeIncoming: netmask is required
```
My values file has
```
lacework:
  laceworkConfig:
    anonymizeIncoming:
      netmask:
```
I am aliasing the dependent upstream chart to lacework

**Comment by laconc** [comment]
Chris, my values right now are:
```
laceworkConfig:
  accessToken:
    existingSecret:
      name: lacework-secrets
      key: ACCESS_TOKEN

  anonymizeIncoming:

  kubernetesCluster: my-cluster
  env: dev
```
