### ISSUE TITLE
Trying to deploy lacework-agent with ArgoCD

### ISSUE THREAD

**Issue by isaaclopezwefox** [lacework/helm-charts#224]
We are facing problems trying to deploy lacework-agent with ArgoCD.

chart.yaml:

```
apiVersion: v2
appVersion: "1.0"
description: Lacework Agent
home: https://www.lacework.com
icon: https://www.lacework.com/wp-content/uploads/2019/07/Lacework_Logo_color_2019.svg
keywords:
- monitoring
- security
- run-time
- metric
- troubleshooting
kubeVersion: '> 1.9.0-0'
maintainers:
- email: info@lacework.net
  name: lacework-support
name: lacework-agent
version: 6.10.4
```

values.yaml:

```
lacework-agent:
  clusterAgent:
    # [Optional] Should we install cluster agent.
    enable: true
    # [Optional] Cluster type.
    clusterType: eks
    # [Optional] Cluster region.
    clusterRegion: xx-xxxxx-x
  laceworkConfig:
    # [Required] An access token is required before running agents.
    # Visit https://<LACEWORK UI URL> for eg: https://lacework.lacework.net
    accessToken: xxxxxxxxxx
    # [Optional] Give your k8s environment a friendly name
    # https://docs.lacework.com/onboarding/add-agent-tags
    env: dev
    # [Optional] Kubernetes cluster name
    # https://support.lacework.com/hc/en-us/articles/360005263034-Deploy-on-Kubernetes
    kubernetesCluster: cluster-dev
    # [Required] Region specific Lacework service URL. Defaults to the US region.
    serverUrl: https://api.fra.lacework.net 
```

ArgoCD error:

```Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = `helm template . --name-template lacework --namespace lacework --kube-version 1.26 --values <path to cached source>/values.yaml <api versions removed> --include-crds` failed exit status 1: Error: template: lacework-agent/templates/_helpers.tpl:38:28: executing "lacework-agent.image" at <.Values.image.registry>: nil pointer evaluating interface {}.registry Use --debug flag to render out invalid YAML```

looks like a issue with the values.schema.json file. Can disable this validation?
We can deploy it successfully through helm cli, seems the values.yaml file is correct.

Stack versions:

```
ArgoCD version v2.9.0+9cf0c69
Helm v3
EKS version 1.26
```

kind regards!
