### ISSUE TITLE
Feature: Having Agent Token secret created externally

### ISSUE THREAD

**Issue by max-hassani** [lacework/helm-charts#256]
Feature: I would like to be able to create the agent token secret externally on K8s cluster.
Issue: currently, when a value for the agent token is not provided while installing the helm chart, it fails to deploy. I would like to make the token value to be optional.

**Comment by max-hassani** [comment]
going through the `values.schema.json` I found that I can pass the existing secret to acces token value, like:
```
  accessToken:
    existingSecret:
      name: "lacework-agent-access-token"
      key: "agent-access-token"
```
