### ISSUE TITLE
Json Schema validation blocking to create parent charts and used this lacework official chart as  dependencies subcharts

### ISSUE THREAD

**Issue by liliwangthescore** [lacework/helm-charts#68]
Hi Lacework support team:
We are facing the issue as below
1. We are using github private repo for our organization so CAN NOT directly using this  lacework official chart
2. We try to create a parent chart, including "this  lacework official chart" as dependencies subcharts, so we still get the newest release / update, and use the "parent chart we created" to deploy by ArgoCD
Below is my parent charts:
```
apiVersion: v2
appVersion: "1.0"
version: 5.5.0
name: lacework-agent
namespace: lacework
description: A Helm chart for Kubernetes Lacework Agent
type: application
icon: https://www.lacework.com/wp-content/uploads/2019/07/Lacework_Logo_color_2019.svg
dependencies:
- name: lacework-agent
  version: 5.5.0
  repository: https://lacework.github.io/helm-charts/
```

And we have a value.yaml file to inject the values
```
lacework-agent:
  laceworkConfig:
    accessToken: XXX
    serverUrl: "https://api.lacework.net"
    fim:
      coolingPeriod: 60
      crawlInterval: 60
      noAtime: true
      runAt: 03:01
  
    kubernetesCluster: XXX
    env: staging
    autoUpgrade: disable
  
  resources:
    requests:
      cpu: 200m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 1024Mi

```

3. When have try to helm template, it would get error as below
```
lacework % helm template -f ./value-dev-staging.yaml lacework-agent ./
Error: values don't meet the specifications of the schema(s) in the following chart(s):
lacework-agent:
- (root): Additional property global is not allowed
```
4. The issue is "parent chart is implicit to share the 'global' values from parent to child", but at https://github.com/lacework/helm-charts/blob/main/lacework-agent/values.schema.json, the **"additionalProperties" is all  false**

    some other helm charts like istio also reporting same issue before, see below 3 links
    https://github.com/istio/istio/pull/35496
    https://github.com/helm/helm/issues/10392
    https://github.com/helm/helm/issues/8489

5. The workaround solution is to either
    A. change all "additionalProperties" to **true**
    B. **delete** values.schema.json files ....

6. Can you please help for this issues? Thanks!~~
