### ISSUE TITLE
fim - coolingPeriod, crawlInterval, noAtime, runAt is MUST request at values.schema.json, but It is only Optional at  official chart

### ISSUE THREAD

**Issue by liliwangthescore** [lacework/helm-charts#72]
Hi All,

I am trying to deploy this helmchart as below config:

```
lacework-agent:
  laceworkConfig:
    accessToken: XXX
    serverUrl: "https://api.lacework.net"

    kubernetesCluster: XXX
    env: staging
    autoUpgrade: disable

  resources:
    requests:
      cpu: 200m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 1024Mi
```

And I see the error as below:

```
lacework % helm template lacework-agent .  -f value-dev-staging.yaml --include-crds
Error: values don't meet the specifications of the schema(s) in the following chart(s):
lacework-agent:
- laceworkConfig.fim: coolingPeriod is required
- laceworkConfig.fim: crawlInterval is required
- laceworkConfig.fim: noAtime is required
- laceworkConfig.fim: runAt is required
```

However as  official chart describe, these parameters should **Optional**:
https://github.com/lacework/helm-charts/blob/main/lacework-agent/values.yaml
```
# [Optional] Configure File Integrity Monitoring
  # https://docs.lacework.com/configure-agent-behavior-in-configjson-file#file-integrity-monitoring-fim-properties
  fim:
    # [Optional] Configure coolingperiod in minutes
    coolingPeriod:
    # [Optional] Configure crawlinterval in minutes
    crawlInterval:
    enable: true
    # [Optional] Configure file paths to ignore
    fileIgnore: []
    # [Optional] Configure file paths to include
    filePath: []
    # [Optional] Set to true to prevent atime from being used in metadata hash computation
    noAtime:
    # [Optional] Run the FIM scan interval at the specifid time of the day (HH:MM)
    runAt:
```

But the **values.schema.json** force us to setup these
https://github.com/lacework/helm-charts/blob/main/lacework-agent/values.schema.json

```
                "fim": {
                    "type": "object",
                    "additionalProperties": false,
                    "required": [
                        "coolingPeriod",
                        "crawlInterval",
                        "enable",
                        "fileIgnore",
                        "filePath",
                        "noAtime",
                        "runAt"
                    ],
```

I already submit the support tickete to lacework vendor and get below answer:

```
Hi Lili,
 
I hope you had a good weekend. My name is Katherine and I've been looking into your questions around enabling FIM. When you enable this feature in the agent there will be an increase in CPU consumption. Since there's a high correlation between number of connections the agent is being asked to monitor this is unique to the workload on that machine, I'd recommend starting with some of the default values outlined below dependent on your needs and we can assist with tuning them if you find the agent is consuming too much CPU or not running often enough.
 
Here's some guidance on what each parameter refers to:
[coolingPeriod](https://docs.lacework.com/configure-agent-behavior-in-configjson-file#mode-property): whether to wait before starting FIM. If desired that this runs immediately, set to 0, otherwise the default should be 60 minutes
[crawlInterval](https://docs.lacework.com/deploy-on-kubernetes#helm-configuration-options): the FIM scan interval (how frequently it scans FIM), the default should be 60 minutes
[noAtime](https://docs.lacework.com/deploy-on-kubernetes#helm-configuration-options): true - when true, the access time of a file is not included in the computation of the hash of the file
[runAt](https://docs.lacework.com/configure-agent-behavior-in-configjson-file#runat-property): 03:01 - by default, FIM is run at a random time of day, to change this behaviour and have FIM run at a specific time, set this parameter
 
It's important to note that if you set the runAt property, this will override the crawlInterval with the effect of it being read as if '0' had been entered.
 
Please let me know if you have any additional questions.
 
Many thanks,
Katherine
```

Special due to below answer, we don't want to setup runAT, SO we **DO NOT WANT** to set up those parameters
```
It's important to note that if you set the runAt property, this will override the crawlInterval with the effect of it being read as if '0' had been entered.
```

They should be all **Optional** parameters, not **required**

Can you please make those parameters NOT must required? Thank you so much for your help and looking forward to hear from you.

Lili

**Comment by cirego** [comment]
Hi @liliwangthescore, the root cause of this issue lies in `helm`. When you specify a `laceworkConfig` option using a `values.yaml` file, Helm does not merge the contents of `laceworkConfig` with the defaults. helm/helm#3486 has more context on this.

There are two suggested workarounds that I have for you.

## Option 1

Copy the default `laceworkConfig` from our `values.yaml` file and use that in your `values.yaml` file. Something like this should work:

```
laceworkConfig:
  accessToken: XXX
  annotations: {}
  labels: {}
  autoUpgrade: disable
  env: staging
  datacollector: enable
  fim:
    coolingPeriod:
    crawlInterval:
    enable: true
    fileIgnore: []
    filePath: []
    noAtime:
    runAt:
  kubernetesCluster: XXX
  proxyUrl:
  serviceAccountName:
  serverUrl: https://api.lacework.net
  stdoutLogging: true
```

Unfortunately, as we add new configuration options, you would be required to update your `values.yaml` file.

## Option 2

Provide the override values as `--set` options, with works both on the command-line and ArgoCD. In your case, that would be:

```
--set laceworkConfig.accessToken=XXX
--set laceworkConfig.kubernetesCluster=XXX
--set laceworkConfig.env=staging
--set laceworkConfig.autoUpgrade=disable
```

If you'd prefer to avoid passing the accessToken on the command-line, you can use an existing secret (#45) instead.

Also, I noticed that you added a `resources` block with values that are lower than our supported minimums. While the agent consumes minimal resources during normal operation, lowering the resource limits can result in loss of security efficacy.

**Comment by liliwangthescore** [comment]
Hi cirego,

Do you mean I left blank for all this args?

fim:
    coolingPeriod:
    crawlInterval:
    enable: true
    fileIgnore: []
    filePath: []
    noAtime:
    runAt:

**Comment by cirego** [comment]
Hi @liliwangthescore, yes, if you add those fields as blank (nil), it should work!

**Comment by liliwangthescore** [comment]
Thank you so much cirego! Let me try.

**Comment by liliwangthescore** [comment]
Hi Cirego,

Tested and below config works. Removed "datacollector: enable" due to values.schema.json NOT allowed

```
lacework-agent:
  laceworkConfig:
    accessToken: XXX
    annotations: {}
    labels: {}
    autoUpgrade: disable
    env: staging
    fim:
      coolingPeriod:
      crawlInterval:
      enable: true
      fileIgnore: []
      filePath: []
      noAtime:
      runAt:
    kubernetesCluster: xxx
    proxyUrl:
    serviceAccountName:
    serverUrl: https://api.lacework.net
    stdoutLogging: true
  
  resources:
    requests:
      cpu: 200m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 1024Mi
```


For this:
resources block with values that are lower than our supported minimums.

Yeah I know that, but org previous is setting as this. I will discuss internal for this. Thanks for suggestion!
